name: School Management
description: A school management app for student records
publish: false

environment:
  flet: ">=0.10.0"

dependencies:
  flet: ^0.10.0

dev-dependencies:
  flet_dev: ^0.10.0

flutter:
  uses-material-design: true
  generate: true